### ISSUE TITLE
Required Admin Mode

### ISSUE THREAD

**Issue by FallenAvatar** [SpeedReflect/Binary#5]
You should not require Admin mode. Yes, I know its needed for people that install into Program Files. No thats not a reasonable reason to require it for everyone else who knows better.

**Comment by FallenAvatar** [comment]
A release that does not stupidly require admin mode, for those who installed their game outside of program files, or taken ownership on the files is available here:

https://github.com/FallenAvatar/Binary/releases/tag/2.5.11.1

**Comment by MaxHwoy** [comment]
Requiring admin mode is a reasonable reason when talking about a community that cannot even read a single Readme file.
